### ISSUE TITLE
Issues in 4.12.2018 Build

### ISSUE THREAD

**Issue by ughstudios** [Bdoom/Veritex#65]
Fixed Duplication of items when logging in and out
Forgot to add back hatchet into our starting items. 

These issues will be fixed in next release.

**Comment by ughstudios** [comment]
If we die and respawn, it looks like we are not getting our level and experience back
![image](https://user-images.githubusercontent.com/1284431/38690154-41744118-3e32-11e8-9081-6f0feaa9d9fd.png)

**Comment by ughstudios** [comment]
Lag, cpu issues, and then finally inventory issues (crafting, weight discrepancies first)

**Comment by HulksGaming** [comment]
inventory gathers correctly ,does not duplicate items . weight seems inaccurate 7.5kg reading in inventory of the total item weight , 5.6kg total weight reading , total weight reading has issue/bug
![desktop screenshot 2018 04 12 - 17 30 20 91](https://user-images.githubusercontent.com/38327164/38691011-791659ae-3e77-11e8-913b-6b825f428c1d.png)

after numerous attempts to reproduce , all weight readings are correct and consistant , wood weighs and reads correctly on its own , thatch , apples , berry , strawberrys , hemp , shirt all do too on there own and all mixed aswell . 2nd photo shows same inventory as previous but with accurate weight reading

![desktop screenshot 2018 04 12 - 20 55 02 77](https://user-images.githubusercontent.com/38327164/38700833-352a82e8-3e94-11e8-9ce0-ea52d7734e77.png)

**Comment by HulksGaming** [comment]
water and food drain rate is too high/quick , i feel it needs to be reduced between 25%-50% .then recheck

**Comment by ughstudios** [comment]
Player name seems to be broken again, not visible. Probably due to PlayerName variable:

![image](https://user-images.githubusercontent.com/1284431/38694111-a265d54e-3e3d-11e8-901d-51f2b4b6267c.png)

**Comment by ughstudios** [comment]
Need to verify that all stats are being saved and that if a player respawns, or logs in and out they should still have all stats.

**Comment by ughstudios** [comment]
Stamina is decreasing? 
![image](https://user-images.githubusercontent.com/1284431/38694320-2da10138-3e3e-11e8-8b60-23f347fb96c8.png)

After dying, and respawning this issue did not occur again. Unable to replicate currently.

**Comment by ughstudios** [comment]
Should make inventory hud widgets be "non focusable" 
![image](https://user-images.githubusercontent.com/1284431/38695570-88c17a54-3e41-11e8-90fd-417e164b364d.png)

**Comment by ughstudios** [comment]
Chat should auto-scroll to bottom if message is too long. 
![image](https://user-images.githubusercontent.com/1284431/38695748-fea4a14c-3e41-11e8-8bf8-f983c9f87a01.png)

**Comment by ughstudios** [comment]
Strange lighting issue with hair, only from certain angles:
![image](https://user-images.githubusercontent.com/1284431/38695845-50f6882a-3e42-11e8-832a-cd25f03a2374.png)

**Comment by HulksGaming** [comment]
character randomly starts punching , normally after doing another action or when holding the action button down to long time

**Comment by HulksGaming** [comment]
logging out and back in , loses quickbar , cant access inventory and character gets stuck running , other people had it where there quick bar was still there and can access inventory but cant move at all . i relogged several times to try cure the issue but my issues still remain 
![desktop screenshot 2018 04 12 - 19 53 54 08](https://user-images.githubusercontent.com/38327164/38698289-75f55710-3e8c-11e8-9283-fcf31f0df7f6.png)     picture doesnt show me hitting the i and tab key for inventory

to reproduce this , i suicide and log out and back in again and it occurs again
1) log out
2) log back in
3) error should occurs (has for 3 people)

previous steps now stacks starter items each log adds a new set 
![desktop screenshot 2018 04 12 - 20 28 11 58](https://user-images.githubusercontent.com/38327164/38699747-cbd58d86-3e90-11e8-8690-4f4fb6fe4dea.png)

**Comment by HulksGaming** [comment]
excessive light beam from these veins 
![desktop screenshot 2018 04 12 - 20 29 30 70](https://user-images.githubusercontent.com/38327164/38699574-4841aab8-3e90-11e8-98ba-010c1babb7ea.png)

**Comment by HulksGaming** [comment]
reduce font and maybe place text feed in bottom right corner under or with or around the crafting feed , very least reduce the font and icon size 

![desktop screenshot 2018 04 12 - 21 48 49 32](https://user-images.githubusercontent.com/38327164/38703562-7b064926-3e9b-11e8-9116-186b7a78df5b.png)

**Comment by ughstudios** [comment]
You should be able to do everything in first person that you can do in third person.

**Comment by ughstudios** [comment]
After we respawn from WorldMap respawning, we should hide mouse cursor

**Comment by ughstudios** [comment]
All issues should be fixed in 4.20 build.
